services:
  collector:
    build:
      context: ./collector
    container_name: collector
  analyzer:
    build:
      context: ./analyzer
    container_name: analyzer
  web:
    build:
      context: ./web
    container_name: web
    ports:
      - "8000:8000"
